name: Automatic Preprocessing

on:
  push:
    branches:
      - main

jobs:
  run-preprocessing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn joblib

      - name: Run Preprocessing Script
        run: python preprocessing/automate_Silvi_Kusuma.py

      - name: Upload Preprocessed Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: preprocessed-paddy-dataset
          path: preprocessing/padi_preprocessing/